yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: pnp
pnpMode: loose
packageExtensions:
  debug@*:
    peerDependencies:
      supports-color: "*"
  webpack@*:
    peerDependencies:
      "@types/json-schema": "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint-import-resolver-node: "*"
  "@types/babel__core@*":
    peerDependencies:
      "@babel/generator": "*"
      "@babel/traverse": "*"
      "@babel/template": "*"
